### ISSUE TITLE
RuntimeError: repeats has to be Long tensor.

### ISSUE THREAD

**Issue by Saartjes** [SortAnon/ControllableTalkNet#1]
Hi, I have a question. I’ve been trying to use controllable Talknet on colab to synthesize speech using an audio reference. This seems to work fine for very short samples but when trying somewhat longer reference audio colab does not seem to work. 

To get around this problem I tweaked some bits of the code to make it run locally on a jupyter notebook. I can use the TTS functionality just fine, however, I am not able to synthesize using reference audio of any length. When I try I get this error message: 
line 437, in <listcomp> tensors=[torch.repeat_interleave(text1, durs1) for text1, durs1 in zip(x, reps)], value=pad, dtype=x.dtype, RuntimeError: repeats has to be Long tensor. 

Is this something you ever encounterd?

**Comment by SortAnon** [comment]
The newest revision should fix this.
