### ISSUE TITLE
Making Online Talknet Interface, More Accessible To Screen Readers

### ISSUE THREAD

**Issue by queenslight** [SortAnon/ControllableTalkNet#2]
FYI:

I would have posted this bug report to the PPP first, but do to said area not having an "audio captcha" for Visually Impaired Anons, this is the next best thing.

After the interface loads and I navigate via the tab key to reach the combo box featuring a list of voices, nothing speaks when I arrow down through said choices. The only way I am able to confirm my choice is to tab once then arrow back by line. Otherwise, I need to shift-tab bak or arrow up to the combo box itself to choose a different voice.

In addition, if there is a way you could please point out where the button is for accessing the folder icon (by mentioning the icon's title), that would be most helpful.

NB. I use the VoiceOver screen reader created by Apple, thus Mileage may vary with other assistive technology products found on either Linux, Windows or mobile.

**Comment by SortAnon** [comment]
I've replaced the dropdowns. They seem to work in Narrator now; let me know if they're still broken in VoiceOver.
> In addition, if there is a way you could please point out where the button is for accessing the folder icon (by mentioning the icon's title)

It's called "Files". If you can't drag-and-drop, there's also a button that opens a file dialog. It's titled "Upload to session storage".

**Comment by queenslight** [comment]
Fantastic work with the pull-down menus.
I see that the slider for changing the voice's pitch also reads better.

Thanks for fixing the above, and the content you upload  on to your YouTube
channel, which I love lots!
 I'll be sure to pass on your excellent tool and work to more blind users
among the world.

Lastly, thanks for describing what that button for uploading files is
called. Using Chrome, it says "Choose a file," though I might be looking at
the wrong button.
#OperatorError

Consider this ticket indeed, closed.

PS. If you wish to do so (since I can't personally because of no audio
captcha), please let them know that a fellow blind/visually impaired brony
would like to thank everyone at the PPP for their dedication and joy on the
project (regardless of what goes on over there).
PSS. A simple suggestion for the PPP to end the drama (may it never happen
again):

Someone makes an Equestria Girl's Pony Preservation sister project. If not
specifically for everything that the PPP does, have said Equestria girls
threads be only for audio/animated stories, just for that MLP universe.
I did see a thread in the 4Chan Catalog for EQG content, though it's only
meant for writing and not audio dramas.
