### ISSUE TITLE
talknet has issues downloading some models if your new to talknet

### ISSUE THREAD

**Issue by tomas122727** [SortAnon/ControllableTalkNet#27]
hello sortanon please solve this issue as new anons come oonto the scene are unable to download the model cause it says download failed when the link is completely fine

**Comment by effusiveperiscope** [comment]
This issue seems to be occurring because the gdown requirement is outdated. Updating to 4.6.0 appears to solve the issue.

**Comment by SortAnon** [comment]
Fixed, thanks.
