### ISSUE TITLE
i ran the setup and this error shows when running talknet.bat

### ISSUE THREAD

**Issue by BisericaOrtodoxa** [SortAnon/ControllableTalkNet#3]
Starting TalkNet server. Close this window to shut down the server.
Traceback (most recent call last):
  File "talknet_offline.py", line 3, in <module>
    from controllable_talknet import *
  File "C:\Users\alex_\Desktop\talknet controller\ControllableTalkNet\controllable_talknet.py", line 5, in <module>
    from jupyter_dash import JupyterDash
ModuleNotFoundError: No module named 'jupyter_dash'

**Comment by SortAnon** [comment]
Run vs_BuildTools.exe from the installers folder. Install "Desktop development with C++", making sure that these components are checked:
![install](https://user-images.githubusercontent.com/56806675/134415721-a397925e-0c23-45c3-af75-ccbc03fb04e8.png)
When that's done, re-run setup.bat. Then try it again. Does that solve the issue?
