### ISSUE TITLE
Notebooks not working due to missing modules

### ISSUE THREAD

**Issue by Dimitar971** [SortAnon/ControllableTalkNet#34]
It appears that the two Google Colab notebooks for training and using Controllable TalkNet do not work properly anymore. I constantly get errors that various modules are missing and even when I add lines to install them manually, some of them still don't work (NeMo in particular). These notebooks used to work for me with no problems before, but not anymore. It appears that many of the dependencies have been updated and function differently. If that is the case, will the notebooks be updated at some point?

**Comment by SortAnon** [comment]
Fixed the inference notebook. The training notebook should work, too.
The reason it broke is because Google bumped the Python version in Colab. Eventually, this'll be too tedious to fix, and I can't guarantee that it'll still work in a year or two.
