### ISSUE TITLE
Weird audio glitches on long notes 

### ISSUE THREAD

**Issue by Prism-V** [SortAnon/ControllableTalkNet#5]
I don't know how to contact you so I thought this was my best bet. I've noticed when using custom voicebanks on long words and long notes it glitches out. The pony singing banks don't have this glitch so I was wondering how to fix this in my own banks. I was also wondering if there's anyway to make or edit the phoneme converter because I was getting vowel conversion errors.

**Comment by SortAnon** [comment]
TalkNet models tend to have issues with drawn-out vowels. The only solution is more/cleaner training data.
>I was getting vowel conversion errors.

Could you clarify? If you want it to pronounce something a certain way, you can type it in ARPABET between curly braces.

**Comment by Prism-V** [comment]
Would using samples with longer vowels in the dataset help the issues with drawn-out vowels?
"I was also wondering if there's anyway to make or edit the phoneme converter because I was getting vowel conversion errors."
What was I was trying to ask is, Is there any possible way to input the dataset transcription list in ARPABET or edit the ARPABET converter when training voices, because some proper nouns and non english words confuse it.

**Comment by SortAnon** [comment]
The current training notebook doesn't support ARPABET. Longer vowels in the training data should help, as should having more data in general. 15 minutes is the the bare minimum for decent results, and the best pony models have 2+ hours.
