### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by tomas122727** [SortAnon/ControllableTalkNet#9]
theres a problem it thinks that there is no tensorflow_hib module not found also when i delete that line from extracts.py it then works but is in some kind of beta and isnt as goiod as the stable build before please fix this, its a major issue

**Comment by tomas122727** [comment]
> theres a problem it thinks that there is no tensorflow_hib module not found also when i delete that line from extracts.py it then works but is in some kind of beta and isnt as goiod as the stable build before please fix this, its a major issue

sorry i mean tensorflow_hub module not found

**Comment by tomas122727** [comment]
also is it a possibility to add derpy and a thew more characters please

**Comment by SortAnon** [comment]
Latest update adds tensorflow-hub to the requirements. 

>some kind of beta and isnt as goiod as the stable build before

If you can point out anything specific, open a new issue with more details.
